### PR TITLE
Add option to create review requests

### LINKED ISSUE #192: Allow the mention bot to hook into review requests in addition to of assignees
New feature, would be nice to have in the mention bot! https://github.com/blog/2291-introducing-review-requests

### LINKED ISSUE #195: Feature: Automatically create Review Requests
Github [recently introduced a Review Request](https://github.com/blog/2291-introducing-review-requests) feature that fits like a glove into mention-bot.

AFAIK there's no API yet, but GitHub will probably launch it sometime soon.

### PR DESCRIPTION
**Pull request by jimmidyson**
This required upgrading the github client node module, which mostly just needed changing `user` -> `owner` in github calls.

Fixes #195, fixes #192.

### CODE REVIEW

**Comment by jimmidyson** [comment]
> I think we should add the new option to the readme too...

https://github.com/facebook/mention-bot/pull/198/files#diff-04c6e90faac2675aa89e2176d2eec7d8R53

**Comment by caarlos0** [comment]
> I think we should add the new option to the readme too...
> https://github.com/facebook/mention-bot/pull/198/files#diff-04c6e90faac2675aa89e2176d2eec7d8R53

sorry, somehow I missed that...

**Comment by vjeux** [comment]
Omg, so good, thanks a lot <3

**Comment by josepjaume** [comment]
This is amazing! 🎉

**Comment by josepjaume** [comment]
Hi @jimmidyson - Mention isn't creating review requests even with the setting enabled. Is there anything I have to take into account?

Thanks!

**Comment by jimmidyson** [comment]
No it just works... Are you sure you're using a recent version that includes this change?

**Comment by josepjaume** [comment]
Oh, I'm using GitHub's deploy. Maybe it isn't updated?

**Pull request merged**
