### PR TITLE
clarify the bot's message (fix #171)

### LINKED ISSUE #171: "annotation information" is slightly confusing
Normally an annotation is considered to be something done manually, so I was a bit confused when I saw the default message saying that the bot analyzed "the annotation information on this pull request".

I agree with the change away from "blame" in #142, and the motivation to defer to git terminology, but I'd offer that the annotations on `git annotate` are actually generated on-the-fly when the command is called, out of metadata present in the repo, rather than annotations that are themselves part of the commits (and even less so the PR, since the important thing is the history of the files *prior* to the PR, not the info in the commits of the PR itself).

How about `By analyzing the history of the files in this PR`? /cc @ZauberNerd @vjeux

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
@vjeux I noted that despite #170 being merged, the period does not yet appear in mentionbot's message -- is there any explicit update step to get the bot to use the new messages? Or were you guys perhaps waiting for this PR so you wouldn't have to do it twice in quick succession?

**Comment by vjeux** [comment]
I need to push the new version to heroku, I was waiting for this pull request to do another push :)

**Comment by vjeux** [comment]
Thanks!

**Comment by vjeux** [comment]
Okay, it has been deployed to heroku, should be good to go. Let me know if it doesn't work.

**Comment by waldyrious** [comment]
Seems to be working already! http://zmoazeni.github.io/gitspective/#/timeline/mention-bot

**Pull request merged**
