### PR TITLE
Refs #185, remove trailing comma for .mention-bot file before JSON parse

### PR DESCRIPTION
**Pull request by jeffreyleeon**
connects #185

### CODE REVIEW

**Comment by vjeux** [comment]
Hey @jeffreyleeon, sorry it took me a few days to review this. Unfortunately, the JSON specification disallows trailing commas. I would rather not start supporting invalid JSON there.

However, it would be awesome to report back on the pull request that the configuration was invalid so that it's easy to spot the error.

Would you mind sending a pull request for that instead? Thanks!

**Comment by hunkim** [comment]
@vjeux Good idea!

**Comment by jeffreyleeon** [comment]
@vjeux That's a nice feature! I will try to give a pull request for this. Thanks!

**Comment by vjeux** [comment]
@jeffreyleeon thanks! I will review it more quickly this time!

**Pull request closed without merging**
