### PR TITLE
Add skipTitle Configuration. Fixes #121

### LINKED ISSUE #121: Feature Request: Skip PR based on Title
## Configuration 

*.mention-bot*
```
{
  "skipTitle": "WIP"
}
```

Using the above configuration (or something similar) would not mention reviewers if the PR Title contains **WIP**.

### PR DESCRIPTION
**Pull request by mattpickle**
Add `skipTitle` configuration option to skip mention-bot if the PR title contains specific text.

Example:
```
{
  "skipTitle": "WIP"
}
```

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by mattpickle** [comment]
Fixes https://github.com/facebook/mention-bot/issues/121

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by vjeux** [comment]
Thanks, the code looks really good 👍

**Pull request merged**
