### PR TITLE
Use GHE config for auth cookies

### LINKED ISSUE #47: Github auth cookies does not work with GH:E
In it's current form it always uses github.com and wouldn't try to auth with a GH:E instance.

### PR DESCRIPTION
**Pull request by Friss**
Fixes #47

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks! Need to figure out why flow doesn't work with require('./package.json')

**Comment by Friss** [comment]
Any ideas? I'm not to familiar with flow and how it works with `require()`s

**Comment by vjeux** [comment]
So, flow doesn't understand require('.json'), https://github.com/facebook/flow/issues/620 I'll merge it in and figure out a way to fix it!

Thanks for the pull request!

**Comment by samwgoldman** [comment]
While peeking at this, I noticed an instance of `{gheHost}.com` and other uses of `gheHost` lead me to believe the `.com` is extraneous. FYI.

**Comment by Friss** [comment]
Yeah that's a copy paste fail in the origin header on my part

**Comment by vjeux** [comment]
Fixed the flow issue here:
https://github.com/facebook/mention-bot/commit/32cafebc926d88c05e99d6abdd1dec91d39af086

**Comment by vjeux** [comment]
Fixed the extra .com here: https://github.com/facebook/mention-bot/commit/b3442c5e66f4c540a15e426f35700a5d5ab70ef2

**Pull request merged**
