### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by mspangdal**
Seems my last changes broke the tests, since it wasnt working properly.  Fixed parseBlame and updated the HTML layout for the ParseBlame1 test and everything looks green again.  Sorry about that!

### CODE REVIEW

**Comment by vjeux** [comment]
Awesome! You are the best. I was about to fix them at some point but I'm glad you just did :)

**Comment by mspangdal** [comment]
No problem,  how do you get travis to run the tests?  It's been starting the run for 40mins now 😕

**Comment by vjeux** [comment]
Strange, I just restarted the build.

**Comment by mspangdal** [comment]
I set up my branch in my travis and it started right away;  https://travis-ci.org/mspangdal/mention-bot/builds/197144671

Weird that it doesnt start.

**Comment by vjeux** [comment]
Let's try to ship it and see if we get an email that yells at us :p

**Pull request merged**
