### PR TITLE
travis: fix caching of local nvm storage

### PR DESCRIPTION
**Pull request by nulltoken**

### CODE REVIEW

**Comment by nulltoken** [comment]
Dearest @facebook-github-bot, thanks a lot for this very clear comment. This is now done. BTW did you pass the Turing test? :stuck_out_tongue_winking_eye:

**Comment by nulltoken** [comment]
@facebook-github-bot :cool: 

I cannot help but notice you didn't answer my previous question. I now realize this may have felt a tad rude question. So, let's reboot and start with some small talk. What's your favorite color? Do you have a facebook account?

**Comment by vjeux** [comment]
Haha, this bot just has hardcoded responses! But would be super cool to use M ai on github :p

**Comment by nulltoken** [comment]
> Haha, this bot just has hardcoded responses! But would be super cool to use M ai on github :p

:+1: you know for slow Sundays... :wink:

**Pull request merged**
