### PR TITLE
Add withLabel configuration

### PR DESCRIPTION
**Pull request by andruby**
Our workflow is to open pull requests early so everyone knows who's working on what. When the PR is ready for review, a specific label is added.

This PR adds functionality to set a label with the `withLabel` configuration. This works best when setting the `actions` configuration to `["labeled"]`.

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by andruby** [comment]
I just signed the CLA.

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by vjeux** [comment]
Looks good, thanks!

**Pull request merged**
